// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_8JviKuubtFB-rxzwuh5TAX_wnH6D--g',
    appId: '1:704915124494:web:abaa8e8b9b1bf0077da75f',
    messagingSenderId: '704915124494',
    projectId: 'restaurant-app-b23fa',
    authDomain: 'restaurant-app-b23fa.firebaseapp.com',
    storageBucket: 'restaurant-app-b23fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79aFUlgzvuSZedS09IK1KDhnxbL8_09U',
    appId: '1:704915124494:android:fb69bcf80fbc58667da75f',
    messagingSenderId: '704915124494',
    projectId: 'restaurant-app-b23fa',
    storageBucket: 'restaurant-app-b23fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-lX8WhL3Gb1hfRCcMkiu7UYcJaotK5w',
    appId: '1:704915124494:ios:83c7af235ad3e15e7da75f',
    messagingSenderId: '704915124494',
    projectId: 'restaurant-app-b23fa',
    storageBucket: 'restaurant-app-b23fa.firebasestorage.app',
    iosBundleId: 'com.ajaynaik.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-lX8WhL3Gb1hfRCcMkiu7UYcJaotK5w',
    appId: '1:704915124494:ios:83c7af235ad3e15e7da75f',
    messagingSenderId: '704915124494',
    projectId: 'restaurant-app-b23fa',
    storageBucket: 'restaurant-app-b23fa.firebasestorage.app',
    iosBundleId: 'com.ajaynaik.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_8JviKuubtFB-rxzwuh5TAX_wnH6D--g',
    appId: '1:704915124494:web:a81394fa7d6a56f97da75f',
    messagingSenderId: '704915124494',
    projectId: 'restaurant-app-b23fa',
    authDomain: 'restaurant-app-b23fa.firebaseapp.com',
    storageBucket: 'restaurant-app-b23fa.firebasestorage.app',
  );
}
